# Use REST Client extension for VS Code to run this file

### Hello world
GET http://localhost:3000

### Create pokemon
POST http://localhost:3000/pokemon
Content-Type: application/json

{
  "name": "Pikachu",
  "type": "Electric",
  "level": 5
}